# Generated automatically from Makefile.in by configure.
#! /bin/sh

SHELL = /bin/sh
CC = gcc
CFLAGS = -I. -g -O -O2 -Wall -Wno-implicit
CPPFLAGS = 
LDFLAGS = 
LIBOBJS = 
.SUFFIXES:
.SUFFIXES: .c .o

OBJ = admesh.o connect.o stl_io.o stlinit.o util.o normals.o shared.o 

all: ./configure $(OBJ)
	$(CC)  -o admesh $(OBJ) -lm 

clean:
	rm -f $(OBJ) admesh core admesh.core core.admesh
	rm -f config.h config.log config.status\
	      config.cache Makefile

